name: Danger
on: 
  pull_request:
    types: [opened, synchronize, edited]
concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Avoid detecting SwiftLint in Package.swift
        run: |
          sed -i -e 's/.*\.package(url: "https:\/\/github\.com\/realm\/SwiftLint".*//g' Package.swift
      - name: Danger
        uses: 417-72KI/danger-swiftlint@43b6256431e50e838b15f0ade42669db00308b0f # v6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
